### ISSUE TITLE
ShellCheck Issues

### ISSUE THREAD

**Issue by shavs** [JacobEvelyn/git-self-blame#2]
Running the main script file, `git-self-blame`, through [ShellCheck](http://shellcheck.net/) (which provides a command-line application as well as a web interface) shows several small issues with the script.

Mainly, I see these as the common issue:

```bash
variable=`date`
```

which should be:

```bash
variable=$(date)
```

ShellCheck provides additional information ([shellcheck-output.txt](https://github.com/JacobEvelyn/git-self-blame/files/1749714/shellcheck-output.txt)).

Otherwise, very nice description of the script, and it works well!

**Comment by JacobEvelyn** [comment]
Hi @shavs! Thanks for the tip! I had no idea ShellCheck was a thing, and am relatively inexperienced with shell scripting in general so I learned a lot making these fixes. 😄
